#!/bin/bash

# This stress test will run for 5 minutes
if [[ ! -f /usr/bin/stress ]]; then
  apt -y install stress
fi

# How many minutes to run for
minutes=5

echo ""
printf "Running test for $minutes minutes"

# Setup our base environment
echo "" > /var/log/nems/nems-stress-temperature.log
echo "" > /var/log/nems/nems-stress-frequency.log
temperature=$(/usr/local/bin/nems-info temperature)
frequency=$(/usr/local/bin/nems-info frequency)
lowtemperature=$temperature
toptemperature=$temperature
lowfrequency=$frequency
topfrequency=$frequency
frequencywhenhot=999999999999

# Bring this NEMS Server to its knees...
cores=$(nproc --all)
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &
stress --cpu $cores --timeout $((${minutes} * 60)) > /dev/null 2>&1 &

iterations=$((${minutes} * 6))
while [ $iterations -gt 0 ];
do
  temperature=$(/usr/local/bin/nems-info temperature)
  frequency=$(/usr/local/bin/nems-info frequency)

  echo $frequency >> /var/log/nems/nems-stress-frequency.log
  if [[ "$frequency" < "$lowfrequency" ]]; then
    lowfrequency=$frequency
  fi
  if [[ "$frequency" > "$topfrequency" ]]; then
    topfrequency=$frequency
  fi

  echo $temperature >> /var/log/nems/nems-stress-temperature.log
  if [[ "$temperature" < "$lowtemperature" ]]; then
    lowtemperature=$temperature
  fi
  if [[ "$temperature" > "$toptemperature" ]]; then
    toptemperature=$temperature
  fi
  if [[ "$temperature" > "80" ]]; then
    if [[ "$frequency" < "$frequencywhenhot" ]]; then
      frequencywhenhot=$frequency
    fi
  fi
  # Total sleep time of 10 seconds, with a period every 2 seconds
  printf "." && sleep 2 && printf "." && sleep 2 && printf "." && sleep 2 && printf "." && sleep 2 && printf "." && sleep 2
  iterations=$(($iterations-1))
done

echo ""
echo ""

echo "Lowest Temperature:  $lowtemperature"
echo "Highest Temperature: $toptemperature"
echo "Slowest Speed: $lowfrequency"
echo "Maximum Speed: $topfrequency"
echo ""
echo "When the board was hot, the frequency was: $frequencywhenhot"
echo ""

averagetemperature=$(awk '{ total += $1; count++ } END { print total/count }' /var/log/nems/nems-stress-temperature.log)
echo "Average Temperature: $averagetemperature (Lower is better)"

averagefrequency=$(awk '{ total += $1; count++ } END { print total/count }' /var/log/nems/nems-stress-frequency.log)
echo "Average Frequency: $averagefrequency (Higher is better)"

echo ""
