#!/bin/bash

    if ! grep -q "PATCH-000005" /var/log/nems/patches.log; then
      cp -f /root/nems/nems-migrator/data/1.5/nagios/plugins/check_rpi_temperature /usr/lib/nagios/plugins/
      echo "PATCH-000005" >> /var/log/nems/patches.log
    else
      echo "This patch is already applied."
    fi



