#!/bin/bash

# Reinstall WMIC (was missing in NEMS 1.5.2 due to NRPE Upgrade)
    if ! grep -q "PATCH-000011" /var/log/nems/patches.log; then
      /root/nems/nems-admin/build/052-wmic
      /root/nems/nems-admin/build/152-nagiosgraph
      /root/nems/nems-admin/build/999-cleanup
      echo "PATCH-000011" >> /var/log/nems/patches.log
    else
      echo "This patch is already applied."
    fi
