#!/bin/bash

# Reinstall WMIC (was missing in NEMS 1.5.2 due to NRPE Upgrade)
    if ! grep -q "PATCH-000011" /var/log/nems/patches.log; then

      # need to install the new wmic via patch 15 rather than the old deprecated installer
      /root/nems/nems-admin/nems-upgrade/patches/000015

      /root/nems/nems-admin/build/152-nagiosgraph
      /root/nems/nems-admin/build/999-cleanup
      echo "PATCH-000011" >> /var/log/nems/patches.log
    else
      echo "This patch is already applied."
    fi
