#!/bin/bash

# Install MRTG
    if ! grep -q "PATCH-000012" /var/log/nems/patches.log; then
      /root/nems/nems-admin/build/065-mrtg
      /root/nems/nems-admin/build/999-cleanup
      echo "PATCH-000012" >> /var/log/nems/patches.log
    else
      echo "This patch is already applied."
    fi
