#!/bin/bash

    if ! grep -q "PATCH-000003" /var/log/nems/patches.log; then
      /root/nems/nems-admin/build/174-networkmanager && /root/nems/nems-admin/build/999-cleanup
    else
      echo "This patch is already applied."
    fi



