#!/bin/bash

    if ! grep -q "PATCH-000007" /var/log/nems/patches.log; then
      /root/nems/nems-admin/build/047-nrpe
      echo "PATCH-000007" >> /var/log/nems/patches.log
    else
      echo "This patch is already applied."
    fi



