#!/bin/bash
# nems-fs-resize
#
# Resize the root filesystem of any SBC
# By Robbie Ferguson - https://baldnerd.com/
# Designed for NEMS Linux - https://nemslinux.com/
#
# Feel free to include this in your projects, but I'd appreciate it
# if the credit was left in place (though you can do whatever you want).
#
# Tip me at https://donate.category5.tv or https://patreon.com/nems
#
#########################################################################

set -e

if [ "$(id -u)" -ne "0" ]; then
  echo "This script requires root."
  exit 1
fi

set -x

# Detect the drive and partition
fulldev=`/bin/mount | /bin/sed -n 's|^/dev/\(.*\) on / .*|\1|p'`
if [[ $fulldev == "" ]]; then
  echo "Could not determine your root device."
  exit 1
fi

rootdev=`echo $fulldev | cut -d "p" -f 1`
if [[ $rootdev == $fulldev ]]; then
  rootdev="${fulldev//[!a-z]/}"
fi

rootpart=`echo $fulldev | cut -d "p" -f 2`
if [[ $rootpart == $fulldev ]]; then
  rootpart="${fulldev//[!0-9]/}"
fi

resize() {
  start=$(fdisk -l /dev/${rootdev}|grep /dev/${rootdev}p${rootpart}|awk '{print $2}')
  # On some boards the boot column will be #2 and the start value will be *, so use column 3 in that case
  if [[ $start == "*" ]]; then
    start=$(fdisk -l /dev/${rootdev}|grep /dev/${rootdev}p${rootpart}|awk '{print $3}')
  fi
  echo $start
  set +e
  fdisk /dev/${rootdev} <<EOF
p
d
$rootpart
n
p
$rootpart
$start

w
EOF
  set -e
  partx -u /dev/${rootdev}
  resize2fs /dev/${rootdev}p${rootpart}
  set +x
}

resize

echo ""

# Log that patch (resize) has been applied to this system
# Activates features such as bootscreen.sh
if [[ -d /var/log/nems ]]; then
  if ! grep -q "PATCH-000002" /var/log/nems/patches.log; then
    echo "PATCH-000002" >> /var/log/nems/patches.log
  fi
fi

# NEMS runs this script on first boot, so if this is NEMS, this entry will be removed
sed -i "s,/root/nems/nems-admin/resize_rootfs/nems-fs-resize,,g" /etc/rc.local

echo "Done! If you don't see the free space, reboot."
