#!/bin/bash
rootdev=`/usr/local/bin/nems-info rootdev`
rootpart=`/usr/local/bin/nems-info rootpart`

# Get the log filename passed from Stage 1.
rslog=$(cat /var/log/nems/resize-logfile.tmp)
rm -f /var/log/nems/resize-logfile.tmp

echo "Stage 2 on ${rootdev}p${rootpart}" >> $rslog

echo "-------- Resize --------" >> $rslog
/sbin/resize2fs /dev/${rootdev}p${rootpart} >> $rslog 2>&1
echo "-------- /Resize -------" >> $rslog

sed -i "s,/root/nems/nems-admin/resize_rootfs/odroid-stage2,,g" /etc/rc.local
echo "Done" >> $rslog
df -h / >> $rslog
# Force FSCK to run at next boot just for good measure
touch /forcefsck

# Log that patch (resize) has been applied to this system
# Activates features such as bootscreen.sh
if ! grep -q "PATCH-000002" /var/log/nems/patches.log; then
  echo "PATCH-000002" >> /var/log/nems/patches.log
fi

sync
reboot
