#!/bin/bash
BOOT=/etc/rc.local
BOOTDEVICE=`ls -l /dev/disk/by-uuid/ | grep 96C3-9298 | awk '{print $11}' | sed "s/\.\.\/\.\.\///" | sed "s/p1//"`

function do_resize
{
	DATE=`date +%Y-%m-%d`
        rsflog=/var/log/nems/resize-$DATE.log
	echo $rsflog > /var/log/nems/resize-logfile.tmp
	echo "Saving the log to $rsflog"
	sleep 4

	p2_start=`/sbin/fdisk -l /dev/$BOOTDEVICE | grep ${BOOTDEVICE}p2 | awk '{print $2}'`
	p2_end=$(((`/sbin/fdisk -l /dev/$BOOTDEVICE | head -n1 | grep -i bytes | awk '{print $5}'`/512)-20))
	echo $p2_end

	/sbin/fdisk /dev/$BOOTDEVICE <<EOF &>> $rsflog
p
d
2
n
p
2
$p2_start
$p2_end
p
w
EOF
	sync && sync
	sed -i "s,/root/nems/nems-admin/resize_rootfs/odroid-stage1,/root/nems/nems-admin/resize_rootfs/odroid-stage2,g" "$BOOT"
	echo > /etc/udev/rules.d/70-persistent-net.rules
}

do_resize
touch /forcefsck
sync
reboot
