#!/bin/bash
# Get the log filename passed from Stage 1.
rslog=$(cat /var/log/nems/resize-logfile.tmp)
rm -f /var/log/nems/resize-logfile.tmp

BOOTDEVICE=`ls -l /dev/disk/by-uuid/ | grep 96C3-9298 | awk '{print $11}' | sed "s/\.\.\/\.\.\///" | sed "s/p1//"`
NEMSPART=${BOOTDEVICE}p2

echo "Stage 2 on $NEMSPART" >> $rslog
e2fsck -y -f /dev/$NEMSPART >> $rslog

echo "-------- Resize --------" >> $rslog
/sbin/resize2fs /dev/$NEMSPART >> $rslog
echo "-------- /Resize -------" >> $rslog

e2fsck -y -f /dev/$NEMSPART >> $rslog
sed -i "s,/root/nems/nems-admin/resize_rootfs/odroid-stage2,,g" /etc/rc.local
echo "Done" >> $rslog
df -h / >> $rslog
reboot
