#!/bin/bash
rootdev=`/usr/local/bin/nems-info rootdev`
rootpart=`/usr/local/bin/nems-info rootpart`

function do_resize
{
	DATE=`date +%Y-%m-%d`
        rsflog=/var/log/nems/resize-$DATE.log
	echo $rsflog > /var/log/nems/resize-logfile.tmp
	echo "Saving the log to $rsflog"
	sleep 4

	part_start=`/sbin/fdisk -l /dev/$rootdev | grep ${rootdev}p${$rootpart} | awk '{print $2}'`
	part_end=$(((`/sbin/fdisk -l /dev/$rootdev | head -n1 | grep -i bytes | awk '{print $5}'`/512)-20))
	echo $part_end

	/sbin/fdisk /dev/$rootdev <<EOF &>> $rsflog
p
d
$rootpart
n
p
$rootpart
$part_start
$part_end
p
w
EOF
	sync && sync
	sed -i "s,/root/nems/nems-admin/resize_rootfs/odroid-stage1,/root/nems/nems-admin/resize_rootfs/odroid-stage2,g" "/etc/rc.local"
	echo > /etc/udev/rules.d/70-persistent-net.rules
}

do_resize
touch /forcefsck

sync
reboot
