#!/bin/bash

# ******
# need to re-write this to remove the dependency on raspi-config
# ******

# Resize Raspberry Pi on first boot
platform=$(/usr/local/share/nems/nems-scripts/info.sh platform)

if (( $platform >= 0 )) && (( $platform <= 9 )); then
  /usr/bin/raspi-config --expand-rootfs > /dev/null 2>&1
fi

/bin/sed -i~ '/\/root\/nems\/nems-admin\/resize_rootfs\/raspi/d' /etc/rc.local

# Log that patch (resize) has been applied to this system
# Activates features such as bootscreen.sh
if ! grep -q "PATCH-000002" /var/log/nems/patches.log; then
  echo "PATCH-000002" >> /var/log/nems/patches.log
fi

sync
reboot
