#!/bin/bash
rootdev=`/usr/local/bin/nems-info rootdev`
rootpart=`/usr/local/bin/nems-info rootpart`

PLATFORM=rock64 # Must match the filename $PLATFORM-stage#

function do_resize
{
	DATE=`date +%Y-%m-%d`
	rsflog=/var/log/nems/resize-$DATE.log
	echo "Saving the log to $rsflog"
	sleep 4

	start=`/sbin/fdisk -l /dev/$rootdev | grep ${rootdev}p${rootpart} | awk '{print $2}'`
	end=$(((`/sbin/fdisk -l /dev/$rootdev | head -n1 | grep -i bytes | awk '{print $5}'`/512)-34))

	/sbin/fdisk /dev/$rootdev <<EOF &>> $rsflog
p
d
$rootpart
n
p
$rootpart
$start
$end
p
w
EOF
	sync && sync
	sed -i "s,/root/nems/nems-admin/resize_rootfs/"'${PLATFORM}'"-stage1,/root/nems/nems-admin/resize_rootfs/"'${PLATFORM}'"-stage2,g" "/etc/rc.local"
	echo > /etc/udev/rules.d/70-persistent-net.rules
}

do_resize

sync
reboot
