#!/bin/bash
rootdev=`/usr/local/bin/nems-info rootdev`
rootpart=`/usr/local/bin/nems-info rootpart`

PLATFORM=rock64 # Must match the filename $PLATFORM-stage#

/sbin/resize2fs /dev/${rootdev}p${rootpart}
sed -i "s,/root/nems/nems-admin/resize_rootfs/"'${PLATFORM}'"-stage2,,g" /etc/rc.local

# Log that patch (resize) has been applied to this system
# Activates features such as bootscreen.sh
if ! grep -q "PATCH-000002" /var/log/nems/patches.log; then
  echo "PATCH-000002" >> /var/log/nems/patches.log
fi

# Is reboot needed on this platform? Do it anyways until can test.
sync
reboot
