#!/bin/bash
BOOTDEVICE=mmcblk1
PARTITION=7
PLATFORM=rock64 # Must match the filename $PLATFORM-stage#

/sbin/resize2fs /dev/${BOOTDEVICE}p${PARTITION}
sed -i "s,/root/nems/nems-admin/resize_rootfs/"'${PLATFORM}'"-stage2,,g" /etc/rc.local

# Log that patch (resize) has been applied to this system
# Activates features such as bootscreen.sh
if ! grep -q "PATCH-000002" /var/log/nems/patches.log; then
  echo "PATCH-000002" >> /var/log/nems/patches.log
fi

# Is reboot needed on this platform? Do it anyways until can test.
sync
reboot
